version: '2'
services:
###################################
#  TRAEFIK
###################################
  traefik:
    image: traefik:chevrotin
    command: >
      --global.checkNewVersion=true
      --global.checkNewVersion=true
      --global.sendAnonymousUsage=true
      --entryPoints.http.address=:80
      --entryPoints.https.address=:443
      --entryPoints.traefik.address=:8080
      --api=true
      --log=true
      --log.level=DEBUG
      --accessLog=true
      --accessLog.filePath=/log/traefik.log
      --accessLog.bufferingSize=100
      --accessLog.filters.statusCodes=400-499
      --providers.docker=true
      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.docker.exposedByDefault=false
      --providers.docker.network=traefik_proxy
      --providers.docker.swarmMode=false
      --providers.file.directory=/rules
      --providers.file.watch=true
      --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      --certificatesResolvers.letsencrypt.acme.email='${MAIL_ADDRESS}'
      --certificatesResolvers.letsencrypt.acme.storage=/acme.json
      --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_DIR/traefik:/etc/traefik/acme
      - $CONFIG_DIR/certs:/certs
      - $CONFIG_DIR/traefik.log:/log
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${ADMIN_URL}"
      - "traefik.backend.port=8080"
      - "traefik.frontend.auth.basic=admin:${passwd_admin}"
      - "traefik.frontend.entryPoints=https,http"   
    container_name: traefik
##########################################
# Portainer 
##########################################
  portainer:
    image: portainer/portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_DIR/portainer:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:${ADMIN_URL};PathPrefixStrip:/portainer"
      - "traefik.backend.port=9000"
      - "traefik.frontend.entryPoints=https,http"    
###########################################
# FTP
###########################################
  ftp:
    image: stilliard/pure-ftpd:hardened
    volumes: 
      - $CONFIG_DIR/ftp:/etc/pure-ftpd/passwd
      - $DATA_DIR:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    container_name: "pure_ftp_seedbox"
############################################
# Postfix
############################################
  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=${BASE_URL}
      - OPENDKIM_DOMAINS=${BASE_URL} ${ADMIN_URL}
    volumes:
      - ${CONFIG_DIR}/postfix:/etc/opendkim/keys
##########################################
# Watchtower
##########################################
  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: v2tec/watchtower
    command: --cleanup --interval 3600

