version: '2'
services:
###################################
#  TRAEFIK
###################################
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --entryPoints='Name:https Address::443 TLS' --entryPoints='Name:http Address::80  Redirect.EntryPoint:https' --acme.entrypoint=https --acme=true --acme.domains="${BASE_URL}, ${ADMIN_URL}" --acme.email="${MAIL_ADDRESS}" --acme.ondemand=true acme.onhostrule=true --acme.storage=/certs/acme.json --acme.httpchallenge.entrypoint=http
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - $CONFIG_DIR/traefik:/etc/traefik/acme
      - $CONFIG_DIR/certs:/certs
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${ADMIN_URL}"
      - "traefik.backend.port=8080"
      - "traefik.frontend.auth.basic=admin:${passwd_admin}"
      - "traefik.frontend.entryPoints=https,http"   
    container_name: traefik
##########################################
# Portainer 
##########################################
  portainer:
    image: portainer/portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_DIR/portainer:/data
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:${ADMIN_URL};PathPrefixStrip:/portainer"
      - "traefik.backend.port=9000"
      - "traefik.frontend.entryPoints=https,http"    
###########################################
# FTP
###########################################
  ftp:
    image: stilliard/pure-ftpd:hardened
    volumes: 
      - $CONFIG_DIR/ftp:/etc/pure-ftpd/passwd
      - $DATA_DIR:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    container_name: "pure_ftp_seedbox"
############################################
# Postfix
############################################
  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=${BASE_URL}
      - OPENDKIM_DOMAINS=${BASE_URL} ${ADMIN_URL}
    volumes:
      - ${CONFIG_DIR}/postfix:/etc/opendkim/keys
##########################################
# Watchtower
##########################################
  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: v2tec/watchtower
    command: --cleanup --interval 3600

