---
CREATE_CNAME_FOR:
  - name: "portainer-server"
    proxied: yes
  - name: "traefik-server"
    proxied: yes
  - name: "netdata-server"
    proxied: yes
  - name: "ftp-server"
    proxied: no
  - name: "jellyfin-server"
    proxied: yes
  - name: "plex-server"
    proxied: yes